### ISSUE TITLE
Fails when running locally (nektos/act)

### ISSUE THREAD

**Issue by lucasconstantino** [secrethub/actions#12]
When running the action locally with [`nextkos/act`](https://github.com/nektos/act/) I get the following error:

```
[Deploy to Netlify/setup-env]   🐳  docker run image=act-secrethub-actions-env-export-v0-1-0:latest entrypoint=[] cmd=[]
| The following environment variables will be populated with secrets from SecretHub:
| [...]
| Encountered an error: could not find credential file. Run `secrethub signup` to create an account. (secrethub.credential_not_exist)
```

I'm setting the SECRETHUB_CREDENTIAL environment variable correctly, and have tested that fact by printing the env var in a `run` step.

**Comment by florisvdg** [comment]
Sorry for the extremely late response, turns out we weren't automatically added as repo watchers – that's fixed now.

So do you still have this problem? And if you do, what's the command you ran? 

Can you try:

```sh
act -s SECRETHUB_CREDENTIAL=$(cat ~/.secrethub/credential)
```
