### ISSUE TITLE
Will you update this action to work with 1password?

### ISSUE THREAD

**Issue by suprnova32** [secrethub/actions#31]
I started using SecretHub specifically because it offered a GitHub action that made it incredibly easy for me to populate environment variables for a Docker deployment. Now that we need to migrate to 1password, I have not yet found a way to accomplish this. 

Will you upgrade the action to support the new Secrets Automation?

**Comment by SimonBarendse** [comment]
Yes, we're working on an integration with GitHub Actions for 1Password and even [partnered with GitHub](https://techcrunch.com/2021/04/13/1password-acquires-secrethub-and-launches-new-enterprise-secrets-management-tool/) :tada:

We'll publish the new integration at https://github.com/1password and I'll share an update here so you know where to find it when it's ready.

Thank you for sharing your interest.

**Comment by SimonBarendse** [comment]
@suprnova32 You can find a GitHub Action to use with 1Password here: https://github.com/1Password/load-secrets-action
