### ISSUE TITLE
GPG error : EXPKEYSIG

### ISSUE THREAD

**Issue by VictorGobel** [secrethub/actions#32]
Hello :) 

Not sure if it's the right place to put this issue (or if it's on your end).

We have an error with GPG during our CI run (Github Actions). Do you need to renew the key ?
I have seen that there is a [trusted=yes] option in the apt installation but when using the github action integration we didn't had to use it.

Error in the Github Actions CI : 

Err:6 https://apt.secrethub.io stable InRelease
  The following signatures were invalid: EXPKEYSIG 425F7AB667B0B1D8 SecretHub <packages@secrethub.io>
Reading package lists...
W: GPG error: https://apt.secrethub.io stable InRelease: The following signatures were invalid: EXPKEYSIG 425F7AB667B0B1D8 SecretHub <packages@secrethub.io>
E: The repository 'https://apt.secrethub.io stable InRelease' is not signed.

How we use the Action : 

            - name: Load Secrets
              uses: secrethub/actions/env-export@v0.2.1
              env:
                  SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB }}
                  MY_TOKEN: secrethub://orga/passwords/my/token

Waiting for your answer :) 
(and sorry again if it's not the right place ;) )

**Comment by SimonBarendse** [comment]
Thanks for filing this @VictorGobel! You're in the right place. We'll look into this and report back when we know more.

**Comment by florisvdg** [comment]
@VictorGobel Apologies for the inconvenience. Could you try again now?

**Comment by SimonBarendse** [comment]
I'm closing this as fixed. Please feel free to re-open if you're still running into this problem.
